[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/login.php"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/register.php"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/logout.php"
  to = "/.netlify/functions/logout"
  status = 200

[[redirects]]
  from = "/process-payment.php"
  to = "/.netlify/functions/process-payment"
  status = 200

[[redirects]]
  from = "/add-product.php"
  to = "/.netlify/functions/add-product"
  status = 200

[[redirects]]
  from = "/success.php"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/setup.php"
  to = "/404.html"
  status = 410
